### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by timodilg** [timodilg/capstone-project#2]
# Value statement

/

# Description (Text, Scribble, Wireframe, Design)

- Set up app structure (Git Repository, Files, React, Styled Components, 3 sites, NavBar)

# Acceptance criteria

- [ ] Git repository is connected
- [ ] React is imported
- [ ] Styled components are imported
- [ ] NavBar with three pages works

# Tasks

- [ ] Create local project folder
- [ ] Connect folder to Github repository
- [ ] Install npm
- [ ] Create app.js and other necessary pages
- [ ] Import react
- [ ] Import styled components
- [ ] Add nav bar with 3 pages

# Size

small
