### ISSUE TITLE
To Do list

### ISSUE THREAD

**Issue by timodilg** [timodilg/capstone-project#3]
# Value statement

As a **user who wants to work or learn**
I need **a timer**
so that **I can have focussed sessions with a fix time limit**

# Description (Text, Scribble, Wireframe, Design)

- timer of 25 min
- play, pause and stop button below

# Acceptance criteria

- [ ] Timer starts if click on play button
- [ ] Timer pauses if click on pause button
- [ ] Timer stops and goes back to start value of 25 minutes if click on stop button
- [ ] Timer with minutes and seconds

# Tasks

- [ ] Create timer component with buttons

# Size

large
