### ISSUE TITLE
Change sound

### ISSUE THREAD

**Issue by timodilg** [timodilg/capstone-project#5]
# Value statement

As a **user who wants to work or learn**
I need **background sound**
so that **I can work more focussed**

# Description (Text, Scribble, Wireframe, Design)

- sound icon below the timer
- 

# Acceptance criteria

- [ ] Timer starts if click on play button
- [ ] Timer pauses if click on pause button
- [ ] Timer stops and goes back to start value of 25 minutes if click on stop button
- [ ] Timer with minutes and seconds

# Tasks

- [ ] Create timer component with buttons

# Size

large
